import { Language } from '../types';

const hiraganaKatakana = /[\u3040-\u309F\u30A0-\u30FF]/;
const cjk = /[\u4E00-\u9FFF]/;
const latin = /[a-zA-Z]/;

export function detectLanguage(text: string): Language {
  const hiraganaCount = (text.match(hiraganaKatakana) || []).length;
  const cjkCount = (text.match(cjk) || []).length;
  const latinCount = (text.match(latin) || []).length;

  if (hiraganaCount > 0) {
    return 'ja';
  }

  if (cjkCount > latinCount) {
    return 'zh';
  }

  if (latinCount > 0) {
    return 'en';
  }

  const englishIndicators = [
    'hello', 'hi', 'thank', 'please', 'sorry', 'help', 'want', 'need',
    'order', 'refund', 'shipping', 'product', 'account',
  ];
  const lowerText = text.toLowerCase();
  if (englishIndicators.some((w) => lowerText.includes(w))) {
    return 'en';
  }

  return 'zh';
}

export const langLabels: Record<Language, { native: string; flag: string; code: string }> = {
  zh: { native: '中文', flag: '🇨🇳', code: 'ZH' },
  en: { native: 'English', flag: '🇺🇸', code: 'EN' },
  ja: { native: '日本語', flag: '🇯🇵', code: 'JP' },
};

export const uiTexts = {
  zh: {
    appTitle: '智能客服系统',
    chatTitle: '智能客服助手',
    chatSubtitle: 'AI 在线为您服务，7x24小时响应',
    inputPlaceholder: '请输入您的问题...',
    send: '发送',
    quickQuestions: '常见问题',
    emotionStatus: '情绪状态',
    newConversation: '新对话',
    language: '语言',
    adminPanel: '管理后台',
    tickets: '工单管理',
    dashboard: '数据面板',
    chatView: '对话界面',
    typing: '客服正在输入',
    ticketCreated: '工单已创建',
    ticketCreatedDesc: '已为您创建服务工单，专员将尽快跟进处理',
    askHuman: '联系人工客服',
    satisfactionTitle: '服务评价',
    satisfactionDesc: '请对本次服务进行评价',
    submit: '提交',
    cancel: '取消',
    search: '搜索...',
    filter: '筛选',
    all: '全部',
    open: '待处理',
    processing: '处理中',
    pending: '待跟进',
    resolved: '已解决',
    closed: '已关闭',
    priority: '优先级',
    urgent: '紧急',
    high: '高',
    medium: '中',
    low: '低',
    assignedTo: '处理人',
    createdAt: '创建时间',
    updatedAt: '更新时间',
    summary: '问题摘要',
    conversation: '对话记录',
    notes: '处理笔记',
    addNote: '添加备注',
    ticketDetails: '工单详情',
    backToList: '返回列表',
    changeStatus: '变更状态',
    assignAgent: '分配处理人',
    totalConversations: '总会话数',
    autoResolutionRate: '自动解决率',
    avgResponseTime: '平均响应时间',
    avgSatisfaction: '平均满意度',
    ticketsCreated: '创建工单数',
    ticketsResolved: '已解决工单',
    emotionDistribution: '情绪分布',
    intentDistribution: '意图分布',
    dailyTrend: '每日趋势',
    calm: '正常',
    concerned: '关注',
    angry: '激动',
    consultation: '咨询',
    complaint: '投诉',
    after_sales: '售后',
    refund: '退款',
    shipping: '物流',
    product_info: '产品',
    account: '账户',
    greeting: '问候',
    noData: '暂无数据',
    viewTicket: '查看工单',
    unassigned: '未分配',
    addNotePlaceholder: '输入处理备注...',
    seconds: '秒',
    conversations: '对话数',
    ticketsLabel: '工单数',
  },
  en: {
    appTitle: 'Smart Customer Service',
    chatTitle: 'AI Customer Assistant',
    chatSubtitle: 'AI online 24/7, ready to help',
    inputPlaceholder: 'Type your question here...',
    send: 'Send',
    quickQuestions: 'Quick Questions',
    emotionStatus: 'Emotion Status',
    newConversation: 'New Chat',
    language: 'Language',
    adminPanel: 'Admin Panel',
    tickets: 'Tickets',
    dashboard: 'Dashboard',
    chatView: 'Chat',
    typing: 'Agent is typing',
    ticketCreated: 'Ticket Created',
    ticketCreatedDesc: 'A service ticket has been created, our agent will follow up soon',
    askHuman: 'Contact Human Agent',
    satisfactionTitle: 'Rate Service',
    satisfactionDesc: 'Please rate your experience',
    submit: 'Submit',
    cancel: 'Cancel',
    search: 'Search...',
    filter: 'Filter',
    all: 'All',
    open: 'Open',
    processing: 'Processing',
    pending: 'Pending',
    resolved: 'Resolved',
    closed: 'Closed',
    priority: 'Priority',
    urgent: 'Urgent',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    assignedTo: 'Assigned To',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
    summary: 'Summary',
    conversation: 'Conversation',
    notes: 'Notes',
    addNote: 'Add Note',
    ticketDetails: 'Ticket Details',
    backToList: 'Back to List',
    changeStatus: 'Change Status',
    assignAgent: 'Assign Agent',
    totalConversations: 'Total Conversations',
    autoResolutionRate: 'Auto Resolution Rate',
    avgResponseTime: 'Avg Response Time',
    avgSatisfaction: 'Avg Satisfaction',
    ticketsCreated: 'Tickets Created',
    ticketsResolved: 'Tickets Resolved',
    emotionDistribution: 'Emotion Distribution',
    intentDistribution: 'Intent Distribution',
    dailyTrend: 'Daily Trend',
    calm: 'Calm',
    concerned: 'Concerned',
    angry: 'Upset',
    consultation: 'Consultation',
    complaint: 'Complaint',
    after_sales: 'After Sales',
    refund: 'Refund',
    shipping: 'Shipping',
    product_info: 'Product',
    account: 'Account',
    greeting: 'Greeting',
    noData: 'No data',
    viewTicket: 'View Ticket',
    unassigned: 'Unassigned',
    addNotePlaceholder: 'Add a note...',
    seconds: 's',
    conversations: 'Conversations',
    ticketsLabel: 'Tickets',
  },
  ja: {
    appTitle: 'インテリジェントカスタマーサービス',
    chatTitle: 'AIカスタマーアシスタント',
    chatSubtitle: 'AIが24時間年中無休で対応',
    inputPlaceholder: 'ご質問を入力してください...',
    send: '送信',
    quickQuestions: 'よくある質問',
    emotionStatus: '感情状態',
    newConversation: '新しいチャット',
    language: '言語',
    adminPanel: '管理画面',
    tickets: 'チケット',
    dashboard: 'ダッシュボード',
    chatView: 'チャット',
    typing: 'エージェントが入力中',
    ticketCreated: 'チケット作成完了',
    ticketCreatedDesc: 'サービスチケットが作成されました。担当者がすぐに対応します',
    askHuman: 'オペレーターに接続',
    satisfactionTitle: 'サービス評価',
    satisfactionDesc: '今回のサービスを評価してください',
    submit: '送信',
    cancel: 'キャンセル',
    search: '検索...',
    filter: 'フィルター',
    all: 'すべて',
    open: '未対応',
    processing: '対応中',
    pending: '保留中',
    resolved: '解決済み',
    closed: '終了',
    priority: '優先度',
    urgent: '緊急',
    high: '高',
    medium: '中',
    low: '低',
    assignedTo: '担当者',
    createdAt: '作成日時',
    updatedAt: '更新日時',
    summary: '概要',
    conversation: '会話履歴',
    notes: 'メモ',
    addNote: 'メモを追加',
    ticketDetails: 'チケット詳細',
    backToList: 'リストに戻る',
    changeStatus: 'ステータス変更',
    assignAgent: '担当者割り当て',
    totalConversations: '総会話数',
    autoResolutionRate: '自動解決率',
    avgResponseTime: '平均応答時間',
    avgSatisfaction: '平均満足度',
    ticketsCreated: '作成チケット数',
    ticketsResolved: '解決チケット数',
    emotionDistribution: '感情分布',
    intentDistribution: '意図分布',
    dailyTrend: '日次トレンド',
    calm: '穏やか',
    concerned: '要注意',
    angry: '怒っている',
    consultation: '問い合わせ',
    complaint: '苦情',
    after_sales: 'アフター',
    refund: '返金',
    shipping: '配送',
    product_info: '製品',
    account: 'アカウント',
    greeting: '挨拶',
    noData: 'データなし',
    viewTicket: 'チケットを見る',
    unassigned: '未割り当て',
    addNotePlaceholder: 'メモを入力...',
    seconds: '秒',
    conversations: '会話数',
    ticketsLabel: 'チケット数',
  },
};

export function t(language: Language): typeof uiTexts.zh {
  return uiTexts[language] as typeof uiTexts.zh;
}
